/*
 *  Name:     Scancodes
 *  Author:   Bruce E. Hall
 *  Date:     26 Aug 2021
 *  
 *  Capture PS2 Keyboard scancodes
 *  Using the "EasyKey" library
 *  
 *  Press a key, and the scancodes
 *  generated by that keypress
 *  are echoed to the serial monitor
 *  
 */

#include <EasyKey.h>                  // https://github.com/bhall66/EasyKey

#define CLOCK_PIN            0        // specify pin for keyboard clock line
#define DATA_PIN             1        // specify pin for keyboard data line
#define BAUDRATE        115200        // specify the serial monitor baud rate

EasyKey kbd;                          // 'kbd' is the keyboard object

void setup()   {     
  kbd.begin(DATA_PIN, CLOCK_PIN);     // initialize keyboard library          
  Serial.begin(BAUDRATE);             // initialize serial monitor
}

void loop() { 
  if (int i=kbd.getScancode()) {      // As soon as a scancode is available,
    Serial.println(i,HEX);            // echo it to the serial monitor
  }
}
